server:
  port: 8088
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useSSL=false
    username: root
    password: 11111111
  session:
    store-type: none      
security:
  basic:
    enabled: false
my:
  validate:
    borwser:
      remenmberMeSecond: 86400
    code:
      image:
        length: 6
        width: 90
        heigth: 25    

